In [1]:
np.random.randint(4,8, [5,5])

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [9]:
A= np.random.randint(4,8, [5,5])

In [7]:
#donc là on a un tableau de 5 lignes et 5 colonnes d'entiers entre 4 et 8

In [11]:
A

array([[4, 7, 6, 7, 4],
       [4, 7, 5, 4, 4],
       [6, 7, 6, 6, 7],
       [5, 6, 5, 4, 6],
       [7, 7, 6, 7, 6]])

In [13]:
A.sum()

143

In [15]:
A.sum(axis=0)

array([26, 34, 28, 28, 27])

In [19]:
B = np.random.randint(4,8, [2,3])
B

array([[6, 4, 7],
       [5, 6, 5]])

In [21]:
B.sum(axis=1)

array([17, 16])

In [23]:
B.min(axis=1)

array([4, 5])

In [27]:
B.argmin(axis=1)

array([1, 0])

In [29]:
B.argsort()

array([[1, 0, 2],
       [0, 2, 1]])