In [1]:
import numpy as np
np.random.seed(0)
A= np.random.randint(0, 100, [3,3])
B=np.random.randint(0, 100, [3,3])

A,B

(array([[44, 47, 64],
        [67, 67,  9],
        [83, 21, 36]]),
 array([[87, 70, 88],
        [88, 12, 58],
        [65, 39, 87]]))

In [5]:
C=np.hstack((A,B))
C

array([[44, 47, 64, 87, 70, 88],
       [67, 67,  9, 88, 12, 58],
       [83, 21, 36, 65, 39, 87]])