In [3]:
import numpy as np
np.random.seed(0)
A= np.random.randint(0, 100, [10,5])

In [5]:
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [7]:
 A[0]


array([44, 47, 64, 67, 67])

In [10]:
A[0,1]


47

In [12]:
A[:0]


array([], shape=(0, 5), dtype=int32)

In [14]:
A[:,0]

array([44,  9, 70, 65, 81,  9, 47, 49, 39, 32])

In [16]:
Prix= A[:,0]

In [18]:
Surface = A[:, 1]

In [20]:
Prix.mean()

44.5

In [22]:
Prix.var()

513.65

In [30]:

    Prix[0]=(Prix[0]-Prix.mean())/Prix.var()

In [32]:
Prix[0]

0

In [34]:
Prix.shape


(10,)

In [60]:
n=Prix.shape[0]
for i in range(9):
    Prix[i]

Prix[i]+1
    

    

1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np